version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'tetoChat'
      MYSQL_ROOT_PASSWORD: '02Mickey$'
    volumes:
      - mysql-volume:/database/db
    restart: always

  api:
    container_name: api-tetoChat
    build: ./api
    restart: always
    ports:
      - '3005:3005'
    depends_on:
      - mysql
    env_file:
      - ./api/.env

  frontend:
    container_name: front-tetoChat
    build: ./front-end
    depends_on:
      - api
    ports:
      - '3000:3000' # Adicionando porta para acessar o frontend diretamente
    volumes:
      - front-volume:/var/www/html
    environment:
      - REACT_APP_API_URL=http://api:3005 # URL para a API

  nginx:
    container_name: nginx-tetoChat
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - front-volume:/var/www/html
    depends_on:
      - api
      - mysql
      - frontend

volumes:
  mysql-volume:
  front-volume:

networks:
  default:
    driver: bridge
