services:

  frontend:
    container_name: front-tetoChat
    build: ./front-end
    volumes:
      - front-volume:/var/www/html
  nginx:
    container_name: nginx-tetoChat
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - front-volume:/var/www/html
    depends_on:
      - frontend


volumes:
  front-volume:


